logging:
  level:
     cn.itcast: debug
    # org.springframework: debug
servlet:
      path:  /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ee
    username: root
    password: root
mybatis:
  configuration:
   # map-underscore-to-camel-case: true
    # mapper-locations:  mapper/*.xml
    type-aliases-package: cn.itcast.pojo
